USE ROLE SECURITYADMIN;
GRANT OWNERSHIP ON TABLE poc TO ROLE SYSADMIN
REVOKE CURRENT GRANTS;

GRANT USAGE ON PROCEDURE table_mod(INT, TEXT, TEXT, TEXT, TEXT, TEXT, BOOLEAN, TEXT, TEXT) 
TO ROLE developer;

USE ROLE SYSADMIN;
USE WAREHOUSE WRITER_WH;
USE ROLE SYSADMIN;
USE DATABASE POC;
USE SCHEMA POC;

USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE EVENT TABLE POC.POC.event_table;
ALTER ACCOUNT SET EVENT_TABLE = POC.POC.event_table;
ALTER DATABASE POC SET LOG_LEVEL = INFO;
ALTER SCHEMA POC.POC SET LOG_LEVEL = INFO;

USE ROLE SECURITYADMIN;
GRANT SELECT ON TABLE POC.POC.event_table TO ROLE developer;
SHOW PARAMETERS LIKE 'LOG_LEVEL' IN DATABASE POC;
SHOW PARAMETERS LIKE 'LOG_LEVEL' IN SCHEMA POC.POC;

