use role developer;
use database SNOWFLAKE_SAMPLE_DATA;
use schema information_schema;



select 
    COLUMN_NAME, DATA_TYPE,*
from SNOWFLAKE_SAMPLE_DATA.information_schema.COLUMNS
where 
    table_name = 'CUSTOMER'
    AND TABLE_SCHEMA = 'TPCDS_SF10TCL'

SELECT CURRENT_DATE();

USE ROLE DEVELOPER;
USE DATABASE POC;
USE SCHEMA POC;

SELECT
    *
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER
LIMIT 10;

DROP TABLE POC.POC.POC_STAGING;
CREATE TABLE POC.POC.POC_STAGING
    (
    C_CUSTOMER_SK NUMBER,
    C_CUSTOMER_ID TEXT NOT NULL PRIMARY KEY,
    C_CURRENT_CDEMO_SK NUMBER,
    C_CURRENT_HDEMO_SK NUMBER NOT NULL,    
    C_CURRENT_ADDR_SK NUMBER,
    C_FIRST_SHIPTO_DATE_SK NUMBER,
    C_FIRST_SALES_DATE_SK NUMBER,
    C_SALUTATION TEXT,
    C_FIRST_NAME TEXT,
    C_LAST_NAME	TEXT,
    C_PREFERRED_CUST_FLAG TEXT,
    C_BIRTH_DAY	NUMBER,
    C_BIRTH_MONTH NUMBER,
    C_BIRTH_YEAR NUMBER,
    C_BIRTH_COUNTRY TEXT,
    C_LOGIN	TEXT,
    C_EMAIL_ADDRESS	TEXT,
    C_LAST_REVIEW_DATE TEXT
    );

INSERT INTO POC.POC.POC_STAGING
SELECT *
    FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER
LIMIT 10;

SELECT *
    FROM POC.POC.POC_STAGING;

DROP TABLE POC.POC.POC_FINAL;    
CREATE TABLE POC.POC.POC_FINAL
    (
    CUSTOMER_SK NUMBER,
    CUSTOMER_ID TEXT NOT NULL PRIMARY KEY,
    CURRENT_CDEMO_SK NUMBER,
    CURRENT_HDEMO_SK NUMBER NOT NULL,    
    CURRENT_ADDR_SK NUMBER,
    FIRST_SHIPTO_DATE_SK TIMESTAMP WITHOUT TIME ZONE,
    FIRST_SALES_DATE_SK TIMESTAMP WITHOUT TIME ZONE,
    SALUTATION TEXT,
    FULLNAME TEXT,
    PREFERRED_CUST_FLAG BOOLEAN,
    BIRTH_DATE DATE,
    BIRTH_COUNTRY TEXT,
    LOGIN TEXT,
    EMAIL_ADDRESS TEXT, 
    LAST_REVIEW_DATE TIMESTAMP WITHOUT TIME ZONE,
    VERSION NUMBER,
    EFFECTIVE_DATE TIMESTAMP WITHOUT TIME ZONE
    );

INSERT INTO POC.POC.POC_FINAL
SELECT
    C_CUSTOMER_SK,
    C_CUSTOMER_ID,
    C_CURRENT_CDEMO_SK,
    C_CURRENT_HDEMO_SK,
    C_CURRENT_ADDR_SK,
    CAST(C_FIRST_SHIPTO_DATE_SK AS TIMESTAMP WITHOUT TIME ZONE) AS FIRST_SHIPTO_DATE_SK,
    CAST(C_FIRST_SALES_DATE_SK AS TIMESTAMP WITHOUT TIME ZONE) AS FIRST_SALES_DATE_SK,
    C_SALUTATION,
    C_FIRST_NAME||' '||C_LAST_NAME AS FULLNAME,
    CASE 
        WHEN C_PREFERRED_CUST_FLAG = 'Y' THEN 1
        ELSE 0
    END AS PREFERRED_CUST_FLAG,
    TO_DATE(C_BIRTH_DAY ||'/'||C_BIRTH_MONTH||'/'||C_BIRTH_YEAR,'DD/MM/YYYY') AS BIRTH_DATE,
    C_BIRTH_COUNTRY,
    COALESCE(C_LOGIN,'UNKNOWN') AS LOGIN,
    LOWER(C_EMAIL_ADDRESS) AS EMAIL_ADDRESS,
    CAST(C_LAST_REVIEW_DATE AS TIMESTAMP WITHOUT TIME ZONE) AS LAST_REVIEW_DATE,
    1 AS VERSION,
    CURRENT_TIMESTAMP AS EFFECTIVE_DATE
FROM POC.POC.POC_STAGING

SELECT *
    FROM POC.POC.POC_FINAL;