USE ROLE SYSADMIN;
CREATE OR REPLACE DATABASE poc;
CREATE OR REPLACE SCHEMA poc; -- should be created with managed access.

USE DATABASE poc;
ALTER SCHEMA poc ENABLE MANAGED ACCESS;
CREATE OR REPLACE TABLE poc
(
    id int,
    description text
);

-- should be createad as SYSADMIN. Ownership to the local role, which should be granted to SYSADMIN. 
CREATE WAREHOUSE READER_WH WITH 
    WAREHOUSE_SIZE = 'X-SMALL'
    MAX_CLUSTER_COUNT = 10-- MULTI_CLUSTER = TRUE AUTOMATICALLY WHEN MAX_CLUSTER_COUNT > 1 
    SCALING_POLICY = 'ECONOMY'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

CREATE WAREHOUSE WRITER_WH WITH 
    WAREHOUSE_SIZE = 'X-SMALL'
    MAX_CLUSTER_COUNT = 10
    SCALING_POLICY = 'ECONOMY'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

--cleaning up
DROP WAREHOUSE WRITER_WH;
DROP WAREHOUSE READER_WH;
DROP DATABASE poc;