USE ROLE ACCOUNTADMIN;
CREATE OR ALTER ROLE reader;
CREATE OR ALTER ROLE writer;

USE ROLE SYSADMIN;
--reader role details
GRANT USAGE ON WAREHOUSE READER_WH TO ROLE reader;
GRANT USAGE ON DATABASE POC TO ROLE reader; -- it should not give the possibility to create new objects
GRANT USAGE ON SCHEMA POC.POC TO ROLE reader;
GRANT SELECT ON ALL TABLES IN SCHEMA POC.POC TO ROLE reader;
GRANT SELECT ON ALL VIEWS IN SCHEMA POC.POC TO ROLE reader;
GRANT SELECT ON FUTURE TABLES IN SCHEMA POC.POC TO ROLE reader;--without managed access it will execute but nothing changes
GRANT SELECT ON FUTURE VIEWS IN SCHEMA POC.POC TO ROLE reader;

--writer role details
GRANT USAGE ON WAREHOUSE WRITER_WH TO ROLE writer;
GRANT USAGE ON DATABASE POC TO ROLE writer;
GRANT USAGE ON SCHEMA POC.POC TO ROLE writer;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA POC.POC TO ROLE writer;
GRANT SELECT ON ALL VIEWS IN SCHEMA POC.POC TO ROLE writer;
GRANT CREATE TABLE ON SCHEMA POC.POC TO ROLE writer;
GRANT CREATE VIEW ON SCHEMA POC.POC TO ROLE writer;
GRANT ALL ON FUTURE TABLES IN SCHEMA POC.POC TO ROLE writer;
GRANT ALL ON FUTURE VIEWS IN SCHEMA POC.POC TO ROLE writer;

-- creating users and managing their roles
USE ROLE ACCOUNTADMIN;
CREATE OR ALTER ROLE developer;
CREATE OR ALTER ROLE analyst;

GRANT ROLE reader TO ROLE analyst;
GRANT ROLE writer TO ROLE developer;

CREATE USER developer
PASSWORD = 'poc123'
MUST_CHANGE_PASSWORD = TRUE;

CREATE USER analyst--PAT is the safest way to authentificate
PASSWORD = 'poc789'
MUST_CHANGE_PASSWORD = TRUE;

GRANT ROLE analyst TO USER analyst;-- each role should be granted to sysadmin. Without it SYSADMIN will ot be able to manage objects created by users roles. 
GRANT ROLE developer TO USER developer;

GRANT ROLE reader TO ROLE SYSADMIN;
GRANT ROLE writer TO ROLE SYSADMIN;
GRANT ROLE analyst TO ROLE SYSADMIN;
GRANT ROLE developer TO ROLE SYSADMIN;

ALTER USER analyst 
    SET 
        DEFAULT_ROLE = analyst
        DEFAULT_WAREHOUSE = READER_WH;
ALTER USER developer 
    SET 
        DEFAULT_ROLE = developer
        DEFAULT_WAREHOUSE = WRITER_WH;

SHOW GRANTS TO USER reader;
SHOW GRANTS TO USER writer;

--cleaning up
DROP USER developer;
DROP USER analyst;
DROP ROLE developer;
DROP ROLE analyst;
DROP ROLE reader;
DROP ROLE writer; 
