CREATE OR ALTER ROLE reader;
CREATE OR ALTER ROLE writer;

GRANT USAGE ON WAREHOUSE READER_WH TO ROLE reader;
GRANT USAGE ON DATABASE POC TO ROLE reader;
GRANT USAGE ON SCHEMA POC.POC TO ROLE reader;
GRANT SELECT ON ALL TABLES IN SCHEMA POC.POC TO ROLE reader;
GRANT SELECT ON ALL VIEWS IN SCHEMA POC.POC TO ROLE reader;
GRANT SELECT ON FUTURE TABLES IN SCHEMA POC.POC TO ROLE reader;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA POC.POC TO ROLE reader;

GRANT USAGE ON WAREHOUSE WRITER_WH TO ROLE writer;
GRANT USAGE ON DATABASE POC TO ROLE writer;
-- Jawnie blokujemy tworzenie schematów
REVOKE CREATE SCHEMA ON DATABASE POC FROM ROLE writer;
-- Blokujemy dostęp do innych baz danych
REVOKE USAGE ON DATABASE SNOWFLAKE FROM ROLE writer;
REVOKE USAGE ON DATABASE SNOWFLAKE_SAMPLE_DATA FROM ROLE writer;
REVOKE USAGE ON DATABASE INFORMATION_SCHEMA FROM ROLE writer;
GRANT USAGE ON SCHEMA POC.POC TO ROLE writer;
GRANT SELECT ON ALL TABLES IN SCHEMA POC.POC TO ROLE writer;
GRANT SELECT ON ALL VIEWS IN SCHEMA POC.POC TO ROLE writer;
GRANT CREATE TABLE ON SCHEMA POC.POC TO ROLE writer;
GRANT CREATE VIEW ON SCHEMA POC.POC TO ROLE writer;
GRANT SELECT ON FUTURE TABLES IN SCHEMA POC.POC TO ROLE writer;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA POC.POC TO ROLE writer;

CREATE OR ALTER ROLE developer;
CREATE OR ALTER ROLE analyst;

GRANT ROLE reader TO ROLE analyst;
GRANT ROLE reader TO ROLE developer;

CREATE USER developer
PASSWORD = 'poc123'
MUST_CHANGE_PASSWORD = TRUE;

CREATE USER analyst
PASSWORD = 'poc789'
MUST_CHANGE_PASSWORD = TRUE;

GRANT ROLE analyst TO USER analyst;
GRANT ROLE developer TO USER developer;
ALTER USER analyst SET DEFAULT_ROLE = analyst;
ALTER USER developer SET DEFAULT_ROLE = developer;

--cleaning up
DROP USER developer;
DROP USER analyst;
DROP ROLE developer;
DROP ROLE analyst;
DROP ROLE reader;
DROP ROLE writer; 
